version: '3'
services: 
    database: 
        image: mysql:5.7
        restart: always
        env_file: 
            - .env
        environment: 
            MYSQL_ROOT_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DATABASE}
        ports: 
            - '3306:3306'
        volumes: 
            - ./db:/var/lib/mysql
        networks: 
            - mysql-compose-networks    
networks: 
    mysql-compose-networks:
        driver: bridge            