/* Modelagem Basica 

CLIENTES 

NOME - CARACTER(30)
CPF - NUMEROCI(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

*/
/* Processos de Modelagem 
FASE 01 E FASE 02 - ADD ADM DE DADOS

MODELAGEM CONCEITUAL - RASCUNHO 
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

FASE 03 - DBA - AD
MODELAGEM FÍSICA - SCRIPTS DE BANCO

*/